:------------------------- WARNING ! ----------------------
:         This file is GENERATED by Instant Rails.
:
: If you need to make changes to this file, you should edit
: the source template file instead. The source template is
: C:\temp\InstantRails\conf_files\use_ruby.cmd
:-----------------------------------------------------------
C:
CD C:\Ruby187
PATH C:\Ruby187\bin;%PATH%
M:
cd \achievements
dir
